### ISSUE TITLE
binary artifacts in repo

### ISSUE THREAD

**Issue by jonathon-love** [mcfanda/jamovi_glm#1]
hey marcello,

some of your module's dependencies require compilation, which means that a separate .jmo file needs to built for each platform. we can provide assistance here if you need. (so you won't be able to provide a single GLM.jmo, and have it work everywhere :/)

your repo also contains platform specific binaries in `build`. you can/should add `build` and `temp` to your `.gitignore` and `.Rbuildignore` files. (you can also get rid of .Rproj.user folder while you're at it).

cheers

**Comment by jonathon-love** [comment]
also, your build directory contains a lot of packages you're (presumably) no longer using. if you delete `build`, let it recreate it, your final module will come down in size. your GLM.jmo is 78mb! where as when i build it here it's only 3mb :)

**Comment by mcfanda** [comment]
ok, thanks, I do it

**Comment by mcfanda** [comment]
The huge build folder is due to the package "car", which the module is built, is installed with all its dependencies. I wish I can get rid of this because is a pain every time a rebuild

**Comment by jonathon-love** [comment]
oh yes, that's by design. we want to bundle all the dependencies in.

i've been meaning to add an optimisation where it doesn't bother zipping the files into the .jmo file if it's being installed (at the moment, it zips them all up, then unzips them into the modules folder). this will speed things up, but i haven't got around to it.
